### ISSUE TITLE
Add `exists` proc to check that a row exists in the db

### ISSUE THREAD

**Issue by moigagoo** [moigagoo/norm#115]
Currently, the way to check for a row is to try to select it and catch the `NotFoundError`.

I propose we add `exists` that runs `select exists(select 1 from TABLE where id=ID)`, which presumably is the fastest way to check for row existence: https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

**Comment by toghrulgasimov** [comment]
It is also possible with count function.
https://github.com/moigagoo/norm/blob/05daa4bc34509b677bb1acb597dc6b20477c5d1a/src/norm/postgres.nim#L219

**Comment by moigagoo** [comment]
Fixed in 2.3.4.
