### ISSUE TITLE
Recent update to 2.3.1 do not list exception exhaustively

### ISSUE THREAD

**Issue by Clonkk** [moigagoo/norm#116]
After updating, I now have an error message : 
```
/home/rcaillaud/.nimble/pkgs/norm-2.3.1/norm/sqlite.nim(148, 103) template/generic instantiation from here
/home/rcaillaud/.nimble/pkgs/norm-2.3.1/norm/sqlite.nim(173, 6) Error: fromRow(obj, get row) can raise an unlisted exception: IOError
       Tip: 120 messages have been suppressed, use --verbose to show them.
```

This prevents me from compiling using latest devel compiler.

Using 2.3.0, I don't have this issue

**Comment by moigagoo** [comment]
@Clonkk Seems like the compiler got smarter in devel and can detect more exceptions than the current stable one :-)

**Comment by moigagoo** [comment]
I can't reproduce that in Docker. testament won't see installed packages with devel compiler:
```
root@03ba68736638:/usr/src/app# testament run tests/sqlite/tdb.nim
FAIL: tests/sqlite/tdb.nim c                                       ( 2.01 sec)
Test "tests/sqlite/tdb.nim" in category "sqlite"
Failure: reNimcCrash
$ /root/.choosenim/toolchains/nim-#devel/bin/nim c --hints:on -d:testing --clearNimblePath --nimblePath:build/deps/pkgs   --nimCache:nimcache/tests/sqlite/tdb.nim_4a8a08f09d37b73795649038408b5f33  tests/sqlite/tdb.nim
Hint: used config file '/root/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/root/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
Hint: used config file '/usr/src/app/tests/config.nims' [Conf]
Hint: used config file '/usr/src/app/tests/sqlite/config.nims' [Conf]
...........................................................................................................
/usr/src/app/src/norm/sqlite.nim(3, 11) Error: cannot open file: ndb/sqlite

FAILURE! total: 1 passed: 0 skipped: 0 failed: 1
```

**Comment by moigagoo** [comment]
No idea why but the `--clearNimblePath` flag that was added to testament makes it not see installed deps

**Comment by Clonkk** [comment]
Probably we have to wait until the dust settles with the new Nimble option to generate cfg file with the path to dependencies.

**Comment by moigagoo** [comment]
Yeah, I'll give it a short a couple of weeks later. So far all I can advise is don't use Norm with Nim devel ¯\\_(ツ)_/¯

Also, this issue inspired me to run the tests with -d:normDebug and it turns out logging adds a potential Exception exception to all procs it's used in.

**Comment by dom96** [comment]
> No idea why but the --clearNimblePath flag that was added to testament makes it not see installed deps.

If you haven't already, you should report this in the Nim repo. If `testament` is aimed at being used by packages then this kind of breakage shouldn't happen.

**Comment by moigagoo** [comment]
> I can't use nimble test because of the testament issue

If running the tests with `nim r` works, there is no issue.

However, this issue exposes another problem: if you compile with `-d:normDebug`, every proc can raise generic `Exception` because the logging functions can.

I hate to add `Exception` to the `raises` list, it's way too generic. And I also don't like the idea of adding a conditional `push` at the top.

What are my options here? Any help would be appreciated.

**Comment by Clonkk** [comment]
@moigagoo Sorry to 'necro' this issue; when upgrading Norm version  I encountered this issue again and could not reproduce (again).

After looking into it in more details, I realized it was caused by some custom function defined to handle my own type : 
Such as (I had several, but it can be simplified as this) : 
```nim
proc dbType[T](T: typedesc[seq[U]]) : string = "BLOB" 
proc dbValue[U](val : seq[U]): DbValue = ...
proc to[U](dbVal : DbValue, T: typedesc[seq[U]]) : seq[U] = ...
```

And those functions can raise.

Personnaly, this lead me to the conclusion that it would be better to **not** specify the raised exception as it clashes with custom serialization / de-serialization proc for custom type. What do you think ?
