### ISSUE TITLE
Ability to insert while ignoring duplicates

### ISSUE THREAD

**Issue by ajusa** [moigagoo/norm#120]
It would be nice to include the "IGNORE" functionality that sqlite has. I don't thing postgresql handles it the exact same though, there are syntax differences. A good example of when that is useful is for inserting lots of data but you only want to keep the unique values. See https://stackoverflow.com/questions/19337029/insert-if-not-exists-statement-in-sqlite/19343100

**Comment by moigagoo** [comment]
Implementing this for SQLite turned out to be trivial but I'm having trouble with Postgres. Created an issue in ndb: https://github.com/xzfc/ndb.nim/issues/19
