### ISSUE TITLE
[FeatureRequest] Add a public "fromRow"-like proc that allows handing a raw SQL statement and only do conversion to any object type

### ISSUE THREAD

**Issue by PhilippMDoerner** [moigagoo/norm#133]
Heyho!

As part of the web application that I am writing I am utilizing sqlite's full text search feature FTS5. It's really useful and provides basic search utilities which means you can do somewhat elaborate searches without needing to add something heavy like elasticsearch.
However, that table looks in DDL something like this:

```nim
CREATE VIRTUAL TABLE search_article_content USING fts5( title, title_rev, body, body_rev, table_name, record_id, campaign_id, guid )
```

And I want to query content on that table with an SQL Query like this 
```sql
            SELECT 
                table_name,
                record_id,
                title,
                body,
                guid,
                bm25(search_article_content, 15) as search_score -- 15 states that a match in the title is 15 times as valuable as a match in the body.
            FROM search_article_content 
            WHERE
                campaign_id = %s
                AND (
                    title MATCH %s
                    OR title_rev MATCH %s
                    OR body MATCH %s
                    OR body_rev MATCH %s
                )
            ORDER BY search_score
            LIMIT %s;
```

All I want from norm at this point, is the functionality of taking my very custom SQL statement, make a db query with it and transforming the data it receives into an object whose type I give it. Not even an object that inherits from `Model` really, since I don't want to infer anything from the model, it's job should solely be to be the transformation target as everything else should be determined by my raw sql query. 

The proc I imagine could have a signature like this:

`rawSelect(con: DbConn, query: SqlQuery, targetEntries: seq[T])` 

T in this scenario explicitly only needs to be an object, nothing more.

Would such a feature even be desirable for norm?

**Comment by PhilippMDoerner** [comment]
Correct me if I'm wrong @moigagoo but given how tightly norm interacts with models, I think conversion of Row to Model is only possible when norm generated the query, correct? So I don't think the conversion of `Row` to a `Model` instance can be used to allow raw Sql to be executed and converted into any object type.

Thus I'm getting the feeling that, if we want such a proc, it would need its own "convert to object" implementation instead of hooking into anything norm has already written.

For my own needs, I have currently solved this by using [`nisane`](https://github.com/enthus1ast/nisane), which tries to do exactly that (albeit some wonky behaviour and its very macro heavy). For something with nisane's API, I can even provide some procs on how I work with them:

```nim
import std/[db_sqlite]
import nisane 
import genericNisaneRepository

export nisane
export sequtils

proc parseRow[T: object](row: Row, containerType: typedesc[T]): T =
  row.to(result, nil)

proc parseRow[T: ref object](row: Row, containerType: typedesc[T]): T =
  result = new(T)
  row.to(result, nil)

proc rawSelect*[T](connection: DbConn, containerType: typedesc[T], sqlQueryString: static string, queryParams: varargs[string]): seq[T] =
    const sqlQuery = sql(sqlQueryString)
    var rows: seq[Row] = connection.getAllRows(sqlQuery, queryParams)
    result = rows.map(row => parseRow(row, T))

  proc rawSingleSelect*[T](connection: DbConn, containerType: typedesc[T], sqlQueryString: static string, queryParams: varargs[string]): T =
    let queryResult = connection.rawSelect(T, sqlQueryString, queryParams)

    case(queryResult.len()):
    of 0:
      raise newException(NotFoundError, "Could not find any rows for query")
    of 1:
      result = queryResult[0]
    else:
      raise newException(InvalidQueryError, fmt"Found more than 1 row for query that expected to find a single row.")
```

Example usage:
```nim

import norm/[model, sqlite]
import constructor/defaults

type Creature* {.defaults.} = ref object of Model
    ##[TableModel of the table of creatures ]##
    name*: string = ""

implDefaults(Creature)
proc newModel*(T: typedesc[Creature]): Creature = newCreature()

let con = open(":memory:", "", "", "")
con.createTables(newModel(Creature))

var c1 = Creature(name: "lula")
var c2 = Creature(name: "lula")
con.createEntry(c1)
con.createEntry(c2)

const query = "SELECT * FROM Creature"
type CreatureObj* = object
  name*: string
  id*: int64

let x = con.rawSelect(CreatureObj, query) # If you try out rawSingleSelect with this query, this will raise an Exception as one would anticipate
echo x.repr
```

This is NOT an implementation suggestion!
For norm we'd naturally need to implement an adjusted version to this, as nisane relies on Row to be defined as `Row = seq[string]` while norm has ndb which defines Row as `Row = seq[DbValue]`.


However, given nisane's existence I see a way how this all could work. It's mostly a mattter of: Do we want it? In my personal opinion, this would be convenient for users in order to also deal with/execute complex SQL (Recursive queries for example, or the search query as above).

**Comment by moigagoo** [comment]
@PhilippMDoerner I've just looked at the fromRow implementation and it's pretty simple: https://github.com/moigagoo/norm/blob/28121e0c334551f4b69e8f18f0f6bd997dc8aeaf/src/norm/private/sqlite/rowutils.nim#L17

The complexity comes from the needing to populate nested models.

I think it shouldn't be hard to implement an dumber version that would just concert every row item to the field type of a provided object. The same conversion rules defined in dbtypes would apply.

**Comment by moigagoo** [comment]
And given that you can actually get a raw Row with just plain ndb select, you could achieve your goal.

One thing that I have concerns about is that this functionality feels alien to the concept of Norm. It's more of a general-purpose util.

**Comment by PhilippMDoerner** [comment]
I agree and I think it's a matter of weighing options.
Django for example provides that functionality, but it also has the goal of always being your only gateway to the database, since it's "signal" concept and various other things hinge on the idea that you don't bypass it .

It's a question of what scope is desired for norm, what the desired vision is, that's why I included the question on whether such a feature would be desired (implement in sqlite/postgres modules), tolerated (e.g. by having such a proc in a general utils module that must be imported separately), or not wanted due to being out of scope.

I'm not sure what the fully desired scope of norm is, thus I'm asking.

**Comment by PhilippMDoerner** [comment]
@moigagoo Could you tell me whether you'd want such a feature? 

I have my own solution for this already with nisane, so I wouldn't want to go through the effort of figuring out how to implement this only for us to reach the conclusion that this is out of scope for norm.

**Comment by moigagoo** [comment]
@PhilippMDoerner I think we already have it?

Here's an example:
```
nim> import norm/model
nim> import norm/sqlite
nim> import norm/private/sqlite/rowutils
nim> type
....   M = ref object of Model
....     name: string
....
nim> let r = @[?"foo", ?1]
nim> var m = M()
nim> m.fromRow(r)
nim> echo m[]
(name: "foo", id: 1)
nim> let rr: Row = m.toRow(force = true)
nim> echo rr
@['foo', 1]
```

**Comment by PhilippMDoerner** [comment]
Nice that we have part of the problem somewhat covered! I likely should write up some docs for that or sth.
However, there are 2 points I would want to bring up:

First, this is only the conversion part. Ideally I'd want to have an entire convenience proc with roughly this signature 
`proc rawSelect[T](connection: DbConn, sqlQuery: string, objectType: typedesc[T], params: varargs[DbValue, dbValue]` so that I can use such a proc for example to do more complicated count statements.
Like 
```nim
const sqlStmt = """
  SELECT COUNT(*)
  FROM wikientries_creature creature
  INNER JOIN wikientries_campaign campaign ON creature.campaign_id = campaign.id
  WHERE campaign.name LIKE ?
"""
let campaignName = "SomeCampaign"
let campaignCreatureCount = connection.rawSelect(sqlStmt, int64, campaignName.dbValue())
```
Or do some obscure joins over 5 tables to aggregate some data in complicated SQL fashion in a single query.
`fromRow` is the lions share of the work in that proc, but a `rawSelect` proc (or whatever its name) would still need to be written (which executes the sql query directly and passes received rows to `fromRow` and returns the output).

Second, the current `fromRow` comes with some limitations that I would want to bypass somehow. These are:
1) The type you want to convert to *must* be a model.
2) Deriving from that the type must be a model, it also means that whatever Row instance you feed `fromRow` it *must* have an "id" column. 
3) Deriving from that the type must be a model, it also means that you can not convert a Row into a value-type object should you want to.

**Comment by PhilippMDoerner** [comment]
I've got a first draft going that currently can't deal with nested objects because hot damn do I not get why it doesn't properly work. I think there's a copy happening somewhere in my other versions that leads to data loss somewhere.

All proc names below are placeholders, I think if we were to include them it might make more sense to just keep calling them `fromRow` and add a "not Model" in the type definition or something.

```nim

func isObject*[T: object | ref object](val: T): bool = true
func isObject*[T: object | ref object](val: Option[T]): bool = true
func isObject*[T: not object and not ref](val: Option[T]): bool = false
func isObject*[T: not object and not ref](val: T): bool = false

func toObjectOptional*[T: object | ref object](val: T): Option[T] = some val
func toObjectOptional*[T: object | ref object](val: Option[T]): Option[T] = val
func toObjectOptional*[T: not object and not ref object](val: Option[T]): Option[T] = none(T)
func toObjectOptional*[T: not object and not ref object](val: T): Option[T] = none(T)

#func to[T: object | ref object, M](obj: T, t: typedesc[M]): M = 

template fieldPairsR(t: untyped) =
  when t is object:
    t.fieldPairs
  else:
    t[].fieldPairs

proc fromRawRowPos[T: object | ref object](obj: var T, row: Row, pos: var Natural, skip: bool = false) =
  for field, value in fieldPairsR(obj):
    echo "chief"
    if isObject(value): # value type is object, so maybe must fill that # object, string, int, float
      var valueOptional = value.toObjectOptional()
      if valueOptional.isSome(): # value has object to fill, try to do so
        # parse row into object
        var valueRef = valueOptional.get()

        # row has no data to give
        let columnIsNull = row[pos].kind == dvkNull
        if columnIsNull:
          #When value is an optional of object give it a null type
          when value is Option:
            when value.get() is object or value.get() is ref object:
              value = none typeof(valueRef)
            #When value is an optional of something else
          

      else: # value contains no object to fill, skip
        inc pos
    
    elif not skip:
      value = row[pos].to(typeof(value))
      inc pos
    
    else:
      inc pos

proc fromRawRow*[T: object | ref object](obj: var T, row: Row) =
  ##[ Populate `Model`_ instance from ``ndb.postgres.Row`` instance.

  Nested `Model`_ fields are populated from the same ``ndb.postgres.Row`` instance.
  ]##

  var pos: Natural = 0
  obj.fromRawRowPos(row, pos)
```

I've been obviously mostly stealing from the code that is already there and just renamed a couple things to make it more understandable for me.
 You might notice it's missing a section right after `val = none typeof(subMod)`:
 ```nim
           inc pos
          subMod.fromRowPos(row, pos, skip = true)  ## Then we skip all the ``row`` values that should've gone into this submodel.

        else:                                       ## If ``row[pos]`` is not a ``NULL``,
          inc pos                                   ##
          subMod.fromRowPos(row, pos) 
```

I can't get it to work. I mean, it doesn't cause compile errors or anything, but it falsely gives you the assumption that nested objects will be correctly parsed, which they won't.

I tried with this code on a local sqlite db of mine:
```nim

type NestIds* = object
  record_id: Option[int64]
  guid: string

type Hit* = ref object
  title: string
  table_name: Option[string]
  record_id: Option[int64]
  guid: string

let con = open("mydb.sqlite3", "", "", "")
let rows = con.getAllRows(sql"SELECT title, table_name, record_id, guid FROM search_article_content LIMIT 10")

var objs: seq[Hit] = @[]
echo Hit().isObject()
for row in rows:
  var obj: Hit = Hit(title: "", table_name: some(""), record_id: some(-1.int64), guid: "")
  obj.fromRawRow(row)
  objs.add(obj)

 #If you don't want to use treeforms pretty print module, just use "echo objs.repr"
print objs
```
And found that `NestedIds` does not get filled properly

**Comment by PhilippMDoerner** [comment]
@moigagoo I've settled on an implementation. 
I think trying to support `object` for this is a fool's errand, precisely as you stated because of nested objects.
Thus I swapped to only supporting `ref object` types.

I originally tried to re-implement it as closely as possible as norm originally did it, but I couldn't quite wrap my head around covering all scenarios that can occur.
In the end, it comes down to basically 3 booleans and their combinations that need to be covered when trying to parse a row-column into an object-field:
1) is the field an object itself?
2) is the field an optional?
3) Does the row contain data or is it null?

For the case of the field being optional, there come 2 more questions into play
4) If the field is an object and an optional, is it "none"?
5) If the field is an object and not an optional, is it nil?

Overall, that leads to 2^3 + 2 scenarios, which I then just coded down in single for-loop and slapped and "increment" at the end.
That was easier for me to grasp overall.
Further, instead of recursively calling for something and skipping stuff, I directly manipulated the row index. "Felt" simpler to me.

```nim
func isObject*[T](val: typedesc[T]): bool {.compileTime.} = T is (object or ref object)  
func isObject*[T](val: T): bool {.compileTime.} = T is (object or ref object)  
func isObject*[T](val: typedesc[Option[T]]): bool {.compileTime.} = T is (object or ref object)  
func isObject*[T](val: Option[T]): bool {.compileTime.} = T is (object or ref object)  
func isEmptyColumn(row: Row, index: int): bool = row[index].kind == dvkNull

func getFieldCount*[T: ref object](t: typedesc[T]): int {.compileTime.} =
  for field in T()[].fields:
    inc result

template fieldPairsR[T: object | ref object](t: typedesc[T]): untyped =
  when T is object:
    T().fieldPairs
  else:
    T()[].fieldPairs

#func to[T: object | ref object, M](obj: T, t: typedesc[M]): M = 

proc fromRawRowPos2[T: ref object](obj: var T, row: Row, rowIndex: var Natural) =
  for fieldName, dummyValue in fieldPairsR(T):
    when isObject(dummyValue):
      when dummyValue is Option:
        if row.isEmptyColumn(rowIndex):
          # Scenario 1) Your field is an optional object and the row data for it is empty --> Set object field to none
          obj.setField(fieldName, none(genericParams(dummyValue.type()).get(0)))
        else:
          var innerObjRef = obj.getField(fieldName)
          # Scenario 2) Your field is an optional object and the row data for it exists and optional is empty --> Keep field as none and skip the row columns
          if innerObjRef.isNone():
            const fieldCount = getFieldCount(genericParams(dummyValue.type()).get(0))
            rowIndex = rowIndex + fieldCount - 1
          # Scenario 3) Your field is an optional object and the row data for it exists and optional exists --> Parse into object
          else:
            var innerInnerOptionRef = innerObjRef.get()
            fromRawRowPos2(innerInnerOptionRef, row, rowIndex)

      else:
        # Scenario 4) Your field is an object and NOT an optional, row data for it is empty --> do nothing, skip this column
        
        # Scenario 5) Your field is an object and NOT an optional, row data for it exists but the object is nil --> do nothing and skip the columns 
        var innerObjRef = obj.getField(fieldName)
        if innerObjRef.isNil():
          const fieldCount = getFieldCount(dummyValue.type())
          rowIndex = rowIndex + fieldCount - 1
        # Scenario 6) Your field is an object and NOT an optional, row data for it exists and the object exists --> parse data into it
        else:
          fromRawRowPos2(innerObjRef, row, rowIndex)    

    elif dummyValue is Option:
      if row.isEmptyColumn(rowIndex):
        # Scenario 7) Your field is NOT an object but an optional and row data for it is empty --> Set non-object field to none
        obj.setField(fieldName, none(genericParams(dummyValue.type()).get(0)))
      else: 
        # Scenario 8) Your field is NOT an object but an optional and row data for it exists --> Check if you should skip the parsing. If no, parse data, if yes, just skip and increment the rowIndex accordingly
        let fieldValue = row[rowIndex].to(typeof(obj.getField(fieldName)))
        obj.setField(fieldName, fieldValue)

    else:
      # Scenario 9) Your field is NEITHER an object NOR an optional and row data for it is empty --> do nothing and leave default initialized field value alone, skip the column
      # Scenario 10) Your field is NEITHER an object NOR an optional and row data for exists --> parse data
      let fieldValue = row[rowIndex].to(typeof(obj.getField(fieldName)))
      obj.setField(fieldName, fieldValue)
    
    inc rowIndex
      

proc fromRawRow2*[T: object | ref object](obj: var T, row: Row) =
  var pos: Natural = 0
  obj.fromRawRowPos2(row, pos)
```

That is surprisingly fast btw. 
Comparing my second implementation here to my first one with benchy gave me around a 10-15% speed up.
```nim

type NestedObj* = ref object
  record_id: Option[int64]
  guid: string

type Hit* = ref object
  title: string
  table_name: Option[string]
  someField: Option[NestedObj]

let con = open("mydb.sqlite3", "", "", "")
let rows = con.getAllRows(sql"SELECT title, table_name, record_id, guid FROM search_article_content")

timeIt fmt"#1 row parsing of '{rows.len()}' records":
  var objs: seq[Hit] = @[]

  for row in rows:
    var obj: Hit = Hit(title: "", table_name: none(string), someField: some(NestedObj(record_id: none(int64), guid: "")))
    obj.fromRawRow1(row)
    objs.add(obj)

  keep(objs)

timeIt fmt"#2 row parsing of '{rows.len()}' records":
  var objs: seq[Hit] = @[]

  for row in rows:
    var obj: Hit = Hit(title: "", table_name: none(string), someField: some(NestedObj(record_id: none(int64), guid: "")))
    obj.fromRawRow2(row)
    objs.add(obj)

  keep(objs)
```

**Comment by PhilippMDoerner** [comment]
Through merging #164 this issue is no longer necessary. We can now fire raw SQL select queries and have the output be parsed into a custom ref object type of our choosing.

Therefore I'm closing the issue.
