### ISSUE TITLE
Add UNIQUE pragma for multiple columns

### ISSUE THREAD

**Issue by ajusa** [moigagoo/norm#136]
Something like 
`UNIQUE(i, j) ON CONFLICT REPLACE` should be possible, with i and j being columns. I think this pragma would need to go on the root level object, rather than a field UNIQUE (which Norm already has).

Feel free to close if you think this is out of scope - I honestly don't mind manually writing schemas and then querying using Norm, that's a good enough interface for me. Clearly it wouldn't be feasible to add all constraints to Norm across the different SQL engines.

**Comment by moigagoo** [comment]
Hi!

Thanks for taking the time to submit the feature request.

It seems like you're talking about two features here:
1. Add the ability to set UNIQUE constraint on multiple columns.
2. Allow to define on conflict behavior in the schema. Currently, you can only do that when calling `insert` in SQLite backend.

Is this correct?

**Comment by PhilippMDoerner** [comment]
Ohhh multi-column uniqueness in general would be great!  I have a whole bunch of these where 2-3 columns together 

Django's ORM enforces that on the ORM level as well and I was about to put "code multi-column-uniqueness into your sqlite database" a todo for my own project. Code-wise speaking, I've honestly no idea how such a feature would be built though.

**Comment by moigagoo** [comment]
> Code-wise speaking, I've honestly no idea how such a feature would be built though.

The only solution I see is add `unique` pragma to the type declaration:
```
type Foo {.unique: [spam, eggs].} = ref object of Model
  spam: string
  eggs: int
  baz: float  
```

**Comment by PhilippMDoerner** [comment]
I think the unique pragma is the nicer API of the two. However, given my still limited knowledge of macro's, would it be possible to have multiple multi-column-unique constraints?
