### ISSUE TITLE
column index pragma

### ISSUE THREAD

**Issue by hamidb80** [moigagoo/norm#180]
Hey, IMO it's very good to index columns just like `{.unique.}` pragma.

```nim
  User = ref object of Model
    email {.index.}: string
```

**Comment by moigagoo** [comment]
Implementation for SQLite is ready. Need to do the Postgres one and update the docs.

**Comment by moigagoo** [comment]
Implementation is ready for both SQLite and Postgres.

Two new pragmas are being introduced: index and uniqueIndex. Both pragmas accept a string value. Fields with the same pragma value are included in the same index.

Somehow the book fails to build now even though I didn't change anything. Nimibook got updated probably. I'll fix that and make a release.
