### ISSUE TITLE
Can be ID columnt created first?

### ISSUE THREAD

**Issue by krab** [moigagoo/norm#191]
Currently, it's always last https://i.imgur.com/2NmEnSO.png 

And nim code looks like:

```nim
type
  User* = ref object of Model
    user_id*: int
    firstname*: string
    lastname*: string
    username*: string

  Feed* = ref object of Model
    channel_id*: string
    playlist_id*: string
    video_id*: string
    name*: string
    url*: string

  UserFeed* = ref object of Model
    user*: User
    feed*: Feed

func newUser*(user_id = 0, firstname = "", lastname = "", username = ""): User =
  return User(user_id: user_id, firstname: firstname, lastname: lastname, username: username)

func newFeed*(channel_id = "", playlist_id = "", video_id = "", name = "", url = ""): Feed =
  return Feed(channel_id: channel_id, playlist_id: playlist_id, video_id: video_id, name: name, url: url)

func newUserFeed*(user = newUser(), feed = newFeed()): UserFeed =
  return UserFeed(user: user, feed: feed)

let dbConn* = open("/home/krab/NimProjects/yatb/test.db", "", "", "")

when isMainModule:
  dbConn.createTables(newUser())
  dbConn.createTables(newFeed())
  dbConn.createTables(newUserFeed())

```

**Comment by moigagoo** [comment]
Column order doesn't mean anything really as far as I know. It's random and you should never rely on it.

What is the problem you're solving?

**Comment by krab** [comment]
> What is the problem you're solving?

No problems at all. Just every single ORM (based on structs->DB) for Go makes ID columns first just it. This is the first time I see random.

**Comment by moigagoo** [comment]
> > What is the problem you're solving?
> 
> No problems at all. Just every single ORM (based on structs->DB) for Go makes ID columns first just it. This is the first time I see random.

What I meant by saying that the column order is random is that the list of columns is unordered in general and can't be relied upon. But I guess in some DBs and in some cases the insertion order would match the order the columns appear in selects.

It shouldn't really be a problem to insert id first. I'm just not seeing the benefit of potentially breaking someone's code with this change.
