### ISSUE TITLE
[Documentation Request] Add examples for using more fancy SQL such as `ORDER BY`, `LIMIT` etc. with `select`

### ISSUE THREAD

**Issue by PhilippMDoerner** [moigagoo/norm#193]
System64 - Flandre Scarlet over at the nim-discord raised a good point about the docs:
There are no examples how to use the more fancy SQL elements that come after "WHERE" and we never make it clear you can use them with `select`.

That lead to them using `rawSelect`, which is **not** the intended usecase. We should add examples for those docs.
HOWEVER, as the `Rows` Section is already pretty large, I'd like to split the `Rows` section up into 3 pages:
- Simple SQL Syntax + Examples to deal with Rows
- Fancy SQL Syntax + Examples to deal with Rows (order by, Limit etc.)
- Selecting Many-to-One/One-to-Many/Many-to-Many relationships

Do I have consensus for that from you @moigagoo?
Just to elaborate on why I'm not just doing it: I just don't want to surprise you ;-)
Simple response or thumbsup/down emoji would suffice.

**Comment by moigagoo** [comment]
> Do I have consensus for that from you @moigagoo?

Sure, sounds reasonable. The only thing I'd change wording-wise is replace “Fancy” with “Advanced.”
