### ISSUE TITLE
Your project was used into HappyX docs ✨

### ISSUE THREAD

**Issue by Ethosa** [moigagoo/norm#200]
Hi, I use `NORM` to write [documentation](https://hapticx.github.io/happyx/#/guide/sqlite) for HappyX web framework

If you can improve `NORM` usage in this docs page, please, send PR 👀

Your work is really awesome, I love it!

**Comment by PhilippMDoerner** [comment]
This is unrelated to the issue in question here, but have you already built an "admin-area" kind of thing for happyX? Because basically once you have an ORM that becomes pretty doable (did it myself for Prologue and it's basically just a bit of playing around with generics to achieve this).

**Comment by Ethosa** [comment]
nope at this moment, but `admin-panel` is nice idea. I know that `Django` have an `admin-panel` 🤔

**Comment by PhilippMDoerner** [comment]
In that case (not to derail too much), if you want to implement something like it, it becomes quite possible with norm.
Or any ORM if the necessary procs are implemented.
Could even make a type-agnostic generic one using nim's `Concept` - Just require the mandatory procs to be implemented and act based on that, regardless of what the type is.

That's one of my future project ideas for "Snorlogue" where I did that with norm for the prologue server. Shouldn't be too hard to do for jester I'd assume.

**Comment by moigagoo** [comment]
@Ethosa I can't find the docs source though. How do I edit the docs?

**Comment by Ethosa** [comment]
@moigagoo here is all database documentation https://github.com/HapticX/happyx/tree/master/examples/website/src/docs/db

**Comment by moigagoo** [comment]
@Ethosa thanks! I must say putting the docs in `examples` is... unconventional 😅 You may want to move them to something more obvious like `docs` 😁

**Comment by moigagoo** [comment]
> pull requests are welcome)

@Ethosa yeah but where do I make the PR to? I can't find the docs source unfortunately :-(
