### ISSUE TITLE
selectAll I don't see it's usage and description in the documentation because it hasn't been added?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [moigagoo/norm#204]

**Comment by moigagoo** [comment]
Hi!

The description for both sqlite and postres modules are available:
- https://norm.nim.town/apidocs/norm/postgres.html#selectAll%2C%2Cseq%5BT%5D
- https://norm.nim.town/apidocs/norm/sqlite.html#selectAll%2C%2Cseq%5BT%5D

The usage examples aren't there but it's practically the same as for a regular select: https://norm.nim.town/tutorial/rows.html

**Comment by moigagoo** [comment]
If I misunderstood your request, please correct me.
