### ISSUE TITLE
May I ask how Norm checks if the table exists?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [moigagoo/norm#205]
```
 if not dbConn.tableExists("User"):
    dbConn.createTable(User)

```

Doesn't norm have a method like tableExists?

**Comment by moigagoo** [comment]
Hi! Thanks for the question.

Norm doesn't offer a proc to check table existence for two reasons:
1. It operates on a higher abstraction level. Tables are just an implementation detail, the main focus is on the object relations.
2. There's already a proc for it in stdlib.

What is the problem you're solving that requires to check for table existence on a type?

**Comment by moigagoo** [comment]
Norm won't attempt to create a table if it already exists: https://github.com/moigagoo/norm/blob/438317e33a8aa0243066092388c079d949f338f8/src/norm/postgres.nim#L155

So you don't have to worry about table duplicates.
