### ISSUE TITLE
Deprecate default and notNull pragmas

### ISSUE THREAD

**Issue by moigagoo** [moigagoo/norm#38]
`default` has been deprecated in https://github.com/moigagoo/norm/pull/33/ because default values are now set for all NOT NULL columns automatically. The only case where this pragma could be useful is if you have a read-only column. To cover this case, specify DEFAULT in dbType.

`notNull` pragma makes no sense after Postres was migrated to ndb: all columns are NOT NULL be default except for Option type.

- [x] `default`
- [x] `notNull`

**Comment by 3n-k1** [comment]
Fixed as of c72f4b2 :)

**Comment by moigagoo** [comment]
Closed per https://github.com/moigagoo/norm/pull/52/
