### ISSUE TITLE
Is there anyway to search for specific object fields

### ISSUE THREAD

**Issue by alaviss** [moigagoo/norm#4]
I'm having an object like this:

```nim
type
  User* = object
    name {.unique.}: string
    password: string
```

Later on I'd want to get the object with `name = "username"` and there doesn't seem to be any integrated method for this. I'm I stuck with executing SQL manually via `dbConn`?

**Comment by moigagoo** [comment]
Right now you can do `User.getMany(1, where="name=username")[0]`.

**Comment by alaviss** [comment]
Well, but there's no way to safely compose that with user-inputted data. I guess I'd just use the `dbConn` and `to` to get the needed data for now.

I've found `nim-orm` which seems to feature a rather [nice syntax][0] for finding data, and it'd be nice if `norm` could have something like that as well.

[0]: https://github.com/nanoant/nim-orm#usage

**Comment by alaviss** [comment]
Ormin even went so far as to have a sql-like dsl for this: https://github.com/Araq/blog/blob/master/ormin.rst

**Comment by alaviss** [comment]
For `getMany` and friends where you can generate a `where` argument, I think a mechanism to bind the `?` to a value would be needed, as more often than not, we search within our database with input from the outside, and blindly inserting them would only results in SQL injection.

**Comment by moigagoo** [comment]
I've been experimenting with different ways to increase safety in queries generated by Norm. Looking for a solution that would not change the existing interface much or be expensive to implement. I hope to share something soon.

**Comment by moigagoo** [comment]
Maybe we can just allow `where` to be a tuple of a string with `?` placeholders and an array of values for them?

**Comment by alaviss** [comment]
Sure. A `tuple[condition: string, params: seq[string]]` sounds easy enough to use. An alternative is to have a ``params: varargs[string, `$`]`` at the end of argument list, like those in `db_*` modules.

**Comment by moigagoo** [comment]
@alaviss I've added `params` arg to `getMany` and `getOne` similar to db_* modules.

However, non-string params are not converted to string as I'd expect them:
```
# in sqlite.nim

      template getOne(obj: var object, where = "id = ?", params: varargs[string, `$`]) {.used.} =
        ##[ Read a record from DB by condition and store it into an existing object instance.

        If multiple records are found, return the first one.
        ]##

        let getOneQuery = genGetOneQuery(obj, where)

        debug getOneQuery, " <- ", params.join(", ")

        let row = dbConn.getRow(getOneQuery, params)

        if row.isEmpty():
          raise newException(KeyError, "Record by condition '$#' with params '$#' not found." %
                             where, params.join(", "))

        row.to(obj)
```
```
# in testsqlite.nim
  proc getBookById(id: string): Book = withDb(Book.getOne parseInt(id))
```
The test fails with:
```
Error: type mismatch: got <type Book, int>
but expected one of:
template getOne(obj: var object; where = "id = ?"; params: varargs[string, `$`])
  first type mismatch at position: 1
  required type: var object
  but expression 'Book' is of type: type Book
proc getOne(T: type; where = "id = ?"; params: varargs[string, `$`]): type
  first type mismatch at position: 2
  required type: string
  but expression 'parseInt(id)' is of type: int

expression: getOne(Book, parseInt(id))
```

Do you know why that happens and how to overcome it?

**Comment by alaviss** [comment]
The error message is self-evident: your template expects `typedesc`, `string`, and `varargs`, but you have only passed in a `typedesc` and an `int`.

This is because prepopulated params are not skipped in Nim, and it's bad style to skip them anw. I suggest keeping the old `typedesc, int` form for backward compatibility. It could just be a mapping to the new interface.

**Comment by moigagoo** [comment]
@alaviss Here's an attempt to provide an API for building safe queries, please review: https://github.com/moigagoo/norm/commit/0204f788ca91a052a35f4f8c0947dfa999203652

Feel free to comment the code and suggest better solutions.
