### ISSUE TITLE
unreachable statement after 'return'

### ISSUE THREAD

**Issue by kidandcat** [moigagoo/norm#51]
**Error:**
norm-1.0.17\norm\sqlite\rowutils.nim(129, 9) Error: unreachable statement after 'return' statement or '{.noReturn.}' proc

**Code:**
```nim
db("msg.db", "", "", ""):
  type
    User = object
      name: string
      email: string
      password: string
      avatar: string
      pushtoken: string
      registration: int64
      chats: string

var email = "user@example.com"
withDb:
  var u = User.getOne("email LIKE '?'", email)
  echo repr u
```

**Comment by moigagoo** [comment]
@kidandcat please try using norm#develop, this should be fixed in https://github.com/moigagoo/norm/pull/35

**Comment by kidandcat** [comment]
Yes, working with #develop branch, thanks
