### ISSUE TITLE
Supports more than one FK per object

### ISSUE THREAD

**Issue by alaviss** [moigagoo/norm#6]
For a table with more than one FK, `norm` currently uses this syntax:

```sql
CREATE TABLE table (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	fk1 integer, FOREIGN KEY (fk1) REFERENCES table1 (id),
	fk2 integer, FOREIGN KEY (fk2) REFERENCES table2 (id)
)
```

Which doesn't work with SQLite. Instead this should be used:

```sql
CREATE TABLE table (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	fk1 integer REFERENCES table1 (id),
	fk2 integer REFERENCES table2 (id)
)
```

**Comment by moigagoo** [comment]
The new syntax breaks tests with a single foreign key.

**Comment by moigagoo** [comment]
My bad. It's not the new syntax, it's this commit that breaks the tests: https://github.com/moigagoo/norm/pull/8/commits/43d44154b0bcfa0ec8f651007f7bd8e2612b98e4

**Comment by moigagoo** [comment]
@alaviss do we need the mentioned commit? Foreign keys are enabled in SQLite by default.

**Comment by moigagoo** [comment]
I've reverted this change and added a test for multiple fks: https://github.com/moigagoo/norm/commit/cc86af30bb9be1df45f0071f866a902c93150542

**Comment by alaviss** [comment]
@moigagoo See https://sqlite.org/foreignkeys.html#fk_enable

(emphasis added)

>  Assuming the library is compiled with foreign key constraints enabled, it must still be enabled by the application at runtime, using the PRAGMA foreign_keys command. For example:
>
>      PRAGMA foreign_keys = ON;
>
> Foreign key constraints are **disabled by default** (for backwards compatibility), so must be enabled separately for each database connection. (Note, however, that future releases of SQLite might change so that foreign key constraints enabled by default. Careful developers will not make any assumptions about whether or not foreign keys are enabled by default but will instead enable or disable them as necessary.)

**Comment by moigagoo** [comment]
@alaviss OK, I think I got this. The tests used to pass because foreign keys were off and the check never happenned. Now, when foreign keys are on, a `UNIQUE` constraint must be added to the field referenced by fk. Similar behavior can be observed in PostgreSQL byt default. Trying to fix the tests at the moment.
