### ISSUE TITLE
[FR] Support for BLOB field

### ISSUE THREAD

**Issue by Clonkk** [moigagoo/norm#66]
First, I must say I'm loving this library !

Is there a possitibility for supporting BLOB type with SQLite ? It would ease the use of Nim for computing / storing large set of datas or image; for instance a Tensor (as defined in Arraymancer) could be converted to a BLOB and inserted into a database.

**Comment by moigagoo** [comment]
> First, I must say I'm loving this library !
Thanks!

> Is there a possitibility for supporting BLOB type with SQLite ? It would ease the use of Nim for computing / storing large set of datas or image; for instance a Tensor (as defined in Arraymancer) could be converted to a BLOB and inserted into a database.
Sure, this could be done. First, however, we should check if ndb supports it since Norm uses ndb. Otherwise, this sounds like a fairly simple feature.
