### ISSUE TITLE
Optimize update

### ISSUE THREAD

**Issue by moigagoo** [moigagoo/norm#73]

**Comment by moigagoo** [comment]
Currently, `update` proc updates all columns for the given model, as well as all the columns for its `Model` fields.

This behavior means there's a major potential performance bottleneck: on large DBs with lots for relations, updating can become a very expensive operation.

It's not really safe to track which fields of the objects were updated or even to perform a `select` before each `update`. So, doing that to generate selective updates is not the way to go.

Which leaves us with basically two options:
1. Let the user specify the columns they want to update manually. This is bullet-proof but also error-prone since we move all responsibility to the user.
2. Add `recursive` flag to `update` to make the updates optionally recursive. This won't help optimize objects with many fields but it will help optimize objects with many relations.


https://forum.nim-lang.org/t/6471#40068

**Comment by moigagoo** [comment]
test notifications

**Comment by AS400JPLPC** [comment]
Hello,
I wish you had talked about commit rollback, record locking, and the processing that this involves with NORM.

Coming from a large system it is important to use them ...
i made a wrapper (to basically solve this type of problem and decimal issues) but i am very far from your job.

I really liked your review in the forum, it was very constructive.

**Comment by moigagoo** [comment]
It seems like the newly added fk pragma helps optimize the mentioned update queries. If you don't want related models to be updated automatically, just don't use Norm's automatic foreign key handling and define foreign keys manually.

**Comment by moigagoo** [comment]
This should be solved by fk pragma in 2.2.1.
