### ISSUE TITLE
Please revert my commits

### ISSUE THREAD

**Issue by 3n-k1** [moigagoo/norm#75]
Due to several issues I have had in the Nim community, as well as general behavior I've noticed from browsing IRC logs, I no longer wish to be associated with the Nim community or Nim projects in any way, including through the use of my code.

As such, I'd like to request that you revert the following commits: `dbf36210459ec638990a28270e0bca155fe62166`, `d5241c186f8ee970f9f1fdd0edbcd56d3d251a54`, `53684a2081cf1e3a68b9bea7773440451f864430`, `c72f4b2b8810c9aa4397ac288809d0f9c11a1566`, `ccc704ff862ec7c762385c5751a59dfbcbb42920`, `c7f96c1c5df7a4d36e547149869b7b9a9ecf109c`, `8326db6cd191827b6ff731028c5a5b237357b0f5`, `a392d88a998ccc03454a27f4a595147abb62df39`, `fa25294b0ac42f4f9682936adf25bf66be6afdac`.

This is by no means a legal threat, simply a request. I would prefer my code not be used, but I can't force you to stop using it.

Apologies for any disruption this may cause.

**Comment by 3n-k1** [comment]
Last time I tried to be as vague as I could people got upset, so here's backstory: The issues I've personally had are not the driving force here. What is the driving force is the community's refusal to be polite at all is disgusting. The IRC logs for July 1st 2020 contain multiple core contributors talking about how they think they should be "more blunt" despite their rudeness driving people away.

I don't want to be associated with that at all.

**Comment by moigagoo** [comment]
I've rewritten Norm from scratch, so there's exactly zero lines of your code in the current version.

Also, thanks for your PR with auto foreign keys. It never worked properly and it was this fact that convinced me to do a rewrite. It was a sign that there was something wrong with Norm architecture that couldn't be addressed with fixes anymore.

**Comment by 3n-k1** [comment]
Thank you for letting me know. I appreciate you letting me work with you in the past, and I apologize for bothering you.
