### ISSUE TITLE
dbValue for DateTime not valid in querying

### ISSUE THREAD

**Issue by xeals** [moigagoo/norm#78]
Minimal example:

```nim
import times
import norm/[model, sqlite]
import sugar

type
  TestTime = ref object of Model
    time: DateTime

proc newTest(): TestTime = TestTime(time: now())

when isMainModule:
  var
    db = getDb()
    t = newTest().dup:
      db.select("TestTime.time <= ?", ?now())
  db.close()
```

Using the latest version installed by `nimble` (2.1.1).

Attempting to compile gives `Error: type mismatch: got <DateTime>`, listing all the other types defined in [`norm/private/sqlite/dbtypes`](https://github.com/moigagoo/norm/blob/develop/src/norm/private/sqlite/dbtypes.nim). Attempting to define my own conversion procs (i.e. copying the `DateTime` func from that file) gives an ambiguous call error:

`Error: ambiguous call; both dbtypes.dbValue(val: DateTime) [declared in ~/.nimble/pkgs/norm-2.1.1/norm/private/sqlite/dbtypes.nim(41, 6)] and database.dbValue(val: DateTime) [declared in ~/dev/test/src/test.nim(5, 8)] match for: (DateTime)`

I haven't had this issue declaring my own conversion methods for other types (e.g., `Time`). The issue doesn't crop up for inserting into the database or creating tables, just in `select` that I've found (so far).

**Comment by moigagoo** [comment]
Sorry for missing this issue! Apparently, I was not "watching" my own repos 😒

**Comment by moigagoo** [comment]
> Attempting to compile gives Error: type mismatch: got <DateTime>, listing all the other types defined in norm/private/sqlite/dbtypes

The procs listed are not the ones from `norm/private/sqlite/dbtypes` but instead the default ones from `ndb`.

The problem is that `dbValue` defined in `norm/private/sqlite/dbtypes` is not imported in your module.

Adding this:
```
func dbValue*(val: DateTime): DbValue = dbValue(val.toTime().toUnixFloat())
```
of this:
```
import norm/private/sqlite/dbtypes
```
solves the issue.

But I think a better solution would be to export `dbtypes` in `sqlite` module so that this code would work out of the box.
