### ISSUE TITLE
Documentation: guide on one to many relationships

### ISSUE THREAD

**Issue by nepeckman** [moigagoo/norm#80]
According to the tutorial:
> Models can relate to each each with one-to-one, one-to-many, many-to-many relations. For example, a CartItem can have many Discounts, whereas as a single Discount can be applied to many Products.

However, I've so far been unable to figure out how to setup a one-to-many model relationship. I saw in another issue that seq/set types are unsupported (understandable), is there another way to define one-to-many? I've tried this approach:

```nim
type A = ref object of Model
  foo: string
type B = ref object of Model
  a1: A
  a2: A
```
Inserting `B` objects work as expected (two entries in table `A`, one entry in table `B` linking to both ids). But when selecting the `B` object, both `a1` and `a2` are populated with the same `a1` data. Not sure if this is a bug, or if I'm making a mistake in my approach. Thanks for the help!

**Comment by moigagoo** [comment]
I've created a demo app that I use to test Norm and Norman more or less olin the wild. It has an example of one to many relation: https://github.com/moigagoo/shop-api/blob/develop/src/app/models/subpurchase.nim

Here, a full purchase is composed of subpurchses, each one covering one line item.

**Comment by PhilippMDoerner** [comment]
@moigagoo Before I start looking at this a question for my understanding:
Norm only traverses along the FK fields and does many-to-one look-ups that way, correct?

In your shop-app for example, it is easy to get `Purchase` from a `Subpurchase` since `Subparchase` has an FK-Field to `Purchase`, so you just throw a `Purchase`-type into that field in your `Subpurchase` model and you're done. If you only have a Subpurchase-id, you can get all the data in 1 query.

The only way I see to get all `Subpurchase` entries for a given `Purchase` if you only have that Purchase-id though is by making 2 queries. The first would be to query the purchase with the id using the `Purchase` Model, and then a second query using the `Subpurchase` model to get all its subpurchase's.

I didn't spot anything in your shop-app on the contrary so far, is my understanding correct?

**Comment by moigagoo** [comment]
@PhilippMDoerner 

> The only way I see to get all Subpurchase entries for a given Purchase if you only have that Purchase-id though is by making 2 queries. The first would be to query the purchase with the id using the Purchase Model, and then a second query using the Subpurchase model to get all its subpurchase's.

If you know the purchase id, you can query its subpurchases with a single query:
```
let subpurchases = @[newSubpurchase()].dup:
  db.select("purchase = ?", purchaseId)
```

It's basically the same as working with plain tables.

**Comment by moigagoo** [comment]
Thank you for the interest in improving the docs. I'll help you in any way I can.

**Comment by PhilippMDoerner** [comment]
Hmm I think there's something I don't understand here, is this subpurchase query equivalent to this SQL (which fetches both the data for a Purchase *and* it's associated Subpurchases at once) ?

```sql
SELECT *
FROM purchase
LEFT JOIN subpurchase ON subpurchase.purchase_id = purchase.id
WHERE purchase.id = <MY_PURCHASE_ID>
```

That's the bit which I am missing, whether you can reduce that down to 1 query or whether you should send something like this as 2 queries (One as `SELECT * FROM purchase WHERE id = <MY_PURCHASE_ID>`, the other as `SELECT * FROM subpurchase WHERE purchase_id = <MY_PURCHASE_ID>`).

This is also relevant for myself since I am rewriting an existing backend from Django to Nim and my tech-stack includes norm. I tend to have data structures that'll output something like this:

```json
{ 
    "creation_datetime" :"2020-06-10T12:00:00Z",
    "update_datetime" :"2020-08-03T16:13:59.656516Z",
    "pk" :3,
    "name" :"Church of Morrigan",
    "leader" :"The First Blade",
    "headquarter" :8,
    "headquarter_details": { 
        "name" :"Morrigan Cathedral",
        "parent_name" :"None",
        "name_full" :"Morrigan Cathedral", "pk" :8 
    },
    "description" : null,
    "members" :[{"pk":12,"name":"Alai"},{"pk":171,"name":"Aredhel"},{"pk":87,"name":"Chapli"},{"pk":10,"name":"Dentor Menethil"},{"pk":107,"name":"James"},{"pk":147,"name":"Marie"},{"pk":48,"name":"Mruvain"},{"pk":11,"name":"Nemia Brickenden"},{"pk":77,"name":"Rellam -Relentless- Serbior"}],
    "images" :[{"image":"/media/article_images/D_DPDkRXYAAgSL3_qeNNHg2.jpeg","name":null,"character_article":null,"creature_article":null,"encounter_article":null,"item_article":null,"location_article":null,"organization_article":3,"article_type":"organization_article","pk":42}],
    "campaign" :1,
    "campaign_details": { "name" :"Aldrune", "pk" :1 }
}
```
And I'm also trying to estimate whether I have to do this in e.g. 1 query, or 3 (One for the main data, one for the images which have an FK to the main model, one for the members which have an FK to the main model)

**Comment by moigagoo** [comment]
> is this subpurchase query equivalent to this SQL (which fetches both the data for a Purchase and it's associated Subpurchases at once) ?

It is. Norm fetches related rows automatically. You can see the SQL generated during `select` call in the docs: https://norm.nim.town/tutorial/rows.html

You can override this behaviour and have more granular control over what you fetch: https://norm.nim.town/fk.html

> And I'm also trying to estimate whether I have to do this in e.g. 1 query, or 3 (One for the main data, one for the images which have an FK to the main model, one for the members which have an FK to the main model)

With Norm, if you have a model that refers to two other models, you'll get the entire `Model` instance populated, including all the referenced Model fields, in a single `select` which maps to a single `SELECT` query with two `JOIN`s.

**Comment by PhilippMDoerner** [comment]
I went over it again and I think I have a better understanding of the limitations and capabilities now.
Below a small example that should demonstrate my current understanding of what norm can do and where the limitations are:

Let's take a setup with 3 models like this:
```nim
type A = ref object of Model
    name: string

type B = ref object of Model
    name: string
    my_BA: A

type C = ref object of Model
    name: string
    my_CA: A
```
What I think I can do with this so far is, given an id of model A:
1) I can start a query from table A to get an entry of model A 
(equivalent to `SELECT * FROM A WHERE id = ?`)
2) I can query entries of model B that are linked to model A and the data of that model A entry
(equivalent to `SELECT * FROM B INNER JOIN A ON A.id = B.my_BA`)
3) I can query entries of model C that are linked to model A and the data of that model A entry
(equivalent to `SELECT * FROM C INNER JOIN A on A.id = C.my_CA`)

I don't think there's a way to get the data of an entry in model A and all instances of model B and C that link to A at the same time. You can either query for entries in model B that link to A, or entries in model C that link to A, but not all three at once.

So this SQL query here I don't think I can express in norm, which would be the limitation that we run itno:
```sql
SELECT *
FROM A
LEFT JOIN B ON A.id = B.my_BA
LEFT JOIN C ON A.id = C.my_CA
WHERE A.id = ?
```

Is my understanding so far correct?

**Comment by PhilippMDoerner** [comment]
@nepeckman 

I'm not sure I am able to repeat your bug.
Here a mini example write up of my own while I was trying to figure stuff out to later write up a PR around the documentation:

Given these models:
```nim
type A = ref object of Model
    name: string

type B = ref object of Model
    name: string
    my_BA1: A
    my_BA2: A
```
Given this short script:
```nim

proc newA(name: string = ""): A = A(name: name)
proc newB(name: string = "", my_BA1: A = newA(), my_BA2: A = newA()): B = B(name:name, my_BA1: my_BA1, my_BA2: my_BA2)

let dbConn: DbConn = open(":memory:", "", "", "")

dbConn.createTables(newA())
dbConn.createTables(newB())

var a1 = newA("a1")
var a2 = newA("a2")

var b1 = newB("b1", a1, a2)
var b2 = newB("b2", a1, a2)
var b3 = newB("b3", a1, a2)

with dbConn:
    insert a1
    insert a2
    insert b1
    insert b2
    insert b3


var allB = @[newB()]
dbConn.selectAll(allB)
echo %*allB
```

You receive this output as you would expect in json:
```json
[
    {
        "name": "b1",
        "my_BA1": { "name": "a1", "id": 1 },
        "my_BA2": { "name": "a2", "id": 2 },
        "id": 1
    },
    {
        "name": "b2",
        "my_BA1": { "name": "a1", "id": 1 },
        "my_BA2": { "name": "a2", "id": 2 },
        "id": 2
    },
    {
        "name": "b3",
        "my_BA1": { "name": "a1", "id": 1 },
        "my_BA2": { "name": "a2", "id": 2 },
        "id": 3
    }
]
```

**Comment by moigagoo** [comment]
> It took me until now to realize, that the limitation I was trying to wrap my head around is what was meant initially when nepeckman wrote:

Tbh, I still don't quite understand what nepeckman meant :-) The code they provided works as you've demonstrated in the previous comment. Maybe, there was a bug that was fixed. It's hard to tell now.

The problem with seqs has little to do with one-to-many relations really.

> So this SQL query here I don't think I can express in norm, which would be the limitation that we run into:
SELECT *
FROM A
LEFT JOIN B ON A.id = B.my_BA
LEFT JOIN C ON A.id = C.my_CA
WHERE A.id = ?

You are correct, you can't do that in Norm. Norm is an ORM meaning it offers object-like abstractions on top of rows. This query however results in a row that doesn't correspond to any object defined in your app. It has fields from A, B, and C, and you just don't have a suitable container type for that.

If you really want that, define D that refers to A, B, and C and select into its instance.

**Comment by moigagoo** [comment]
I hope my explanation makes sense. If you want, we can have a Zoom meeting and I'll explain Norm mechanics better.

If I want people to contribute to the docs, it's in my best interest to explain Norm as well as possible :-)

**Comment by nepeckman** [comment]
> @nepeckman
> 
> I'm not sure I am able to repeat your bug.

I think it was a bug that was fixed a while back, sorry for confusing the issue!

**Comment by PhilippMDoerner** [comment]
@moigagoo It does, at least I think I understand your point.

The implication that your suggestion has is, that it would mean not just creating the model D, but also creating an SQL Table D that contains these foreign keys. (The reason why I make this distinction is because in my current web-sideproject I have a *bunch* of models for each table that I explicitly only use for Select statements to only get the specific set of data I want and nothing more).

The only way around creating an actual table D would be to make a view D that contains that data, hmmmmmm

**Comment by moigagoo** [comment]
> The implication that your suggestion has is, that it would mean not just creating the model D, but also creating an SQL Table D that contains these foreign keys.

That's right: type D means table D.

> The reason why I make this distinction is because in my current web-sideproject I have a bunch of models for each table that I explicitly only use for Select statements to only get the specific set of data I want and nothing more

I wonder if you can achieve that by creating several Models that point to the same table using `tableName` pragma 🤔: https://norm.nim.town/models.html

I never tried that but _theoretically_ if you use a model whose fields correspond only to a subset of the columns in a table, `select` calls should work fine and just fetch the columns that are referred to by the model fields. This way you could have multiple models for a single table and get various data slices through them.

**Comment by PhilippMDoerner** [comment]
It works, not just theoretically. Have a demonstration here:
https://github.com/PhilippMDoerner/NimStoryFont/blob/master/src/applications/character/characterModel.nim

I actually thought that was designed with that intention in mind from the get go since it worked flawlessly :-D

**Comment by PhilippMDoerner** [comment]
I believe this issue can be closed, overall? The original issue was fixed some time ago and the issue we turned this into (adding docs) has also been resolved. So this is pretty much done.
