### ISSUE TITLE
Switch from nimble test to testament

### ISSUE THREAD

**Issue by moigagoo** [moigagoo/norm#84]
https://nim-lang.github.io/Nim/testament.html

**Comment by Clonkk** [comment]
I have a branch where both nimble and testament pass all tests. It also cleans up the tests added for foreign keys.
 
Here's the PR : https://github.com/moigagoo/norm/pull/94

I haven't modified travis to run with testament so you can make the change whenever you want.

**Comment by moigagoo** [comment]
Moving to testament of something I'm not sure of. Also, the statement in the title is just wrong: it's not unittest vs testament, it's nimble's test runner vs testament. I didn't research the topic well enough.

So, what I'm doing now is removing testament comments from tests to keep things clear.

I like when one PR fixes one problem, it's easier to review that way. Refactoring tests is a separate task, so I'm removing its implementation from develop _for now_.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
