### ISSUE TITLE
How to get all rows, withouth any condition?

### ISSUE THREAD

**Issue by enthus1ast** [moigagoo/norm#85]
How to get all rows, withouth any condition?

**Comment by enthus1ast** [comment]
a workaround seems to be:

```nim
  db.select(rows, "MyType.id")
  for row in rows:
    echo row[]
```

**Comment by moigagoo** [comment]
@enthus1ast the workaround would be `db.select(rows, "TRUE")` for Postgres or `db.select(rows, "1")` for SQLite. In other words, you just provide a condition that is always true.

Maybe it would be useful to have `selectAll` funcs specifically to select all rows. Feel free to submit a PR.

But I'd also like to notice that selecting all rows is a dangerous operation and you don't want to have it in your business logic. It may work well for small DBs but as your data grows, this will become a nasty bottleneck.

**Comment by Clonkk** [comment]
On the same topic, Is there a way to select specific fields for all rows in a table without loading the full object ?

For example getting all existing ids from a table ?

**Comment by moigagoo** [comment]
> Sorry if it's trivial

@Clonkk unfortunately, it's far from trivial. In fact, it's impossible in both legacy Norm and the new version.

I think, your best course of action to fetch all ids from a table is it use raw sql exec, something like:
```
withDb:
  let ids = dbConn.getAllRows sql"SELECT id FROM TableName"
```
(I don't remember the exact syntax in Norm 1.3.2 but you get the gist)

**Comment by moigagoo** [comment]
Adding `selectAll` in https://github.com/moigagoo/norm/pull/90
