### ISSUE TITLE
Unique and Foreign Key pragma ?

### ISSUE THREAD

**Issue by Clonkk** [moigagoo/norm#87]
Hello,

I don't see any foreign key or unique pragma for Model definition.

I know that for Foreign key are handled by using a Model as a field.

```nim
type
  A = ref object of Model
    field : string # stirng of size 1024*1024*1024

  B = ref object of Model
    a: A
```

But this approach can have some issues (unless I'm mistaken): 
* You have to load the full object in memory. For large objects (that can also contains foreign key) it's a problem.
* You can't create foreign key on anything else than the id field.

I think there are valid use case for wanting this :   
```nim
type
  A = ref object of Model
    field : string 
    name {. unique .}: string

  B = ref object of Model
    a {. fk: A.id .}: int
```

Or this : 
```nim
type
  A = ref object of Model
    name {. unique .}: string

  B = ref object of Model
    a {. fk: A.name .}: int
```

**Comment by moigagoo** [comment]
This is the way it used to be done in Norm 1. You had to create those foreign keys manually, and it was a PITA to instantiate objects with other objects as fields.

So I've taken a more opinionated approach with Norm 2 and made it less flexible but more predictable and reliable.

Adding unique pragma should be trivial. I don't have the time now and I'm focusing on the issue with fetching NULL values. So feel free to send a PR.

I also think it is possible to add customizable foreign keys but this is something I probably won't have the time to invest into any time soon.

**Comment by Clonkk** [comment]
> You had to create those foreign keys manually, and it was a PITA to instantiate objects with other objects as fields.

Yes, I agree using manually declared foreign key is more work than your current solution; but I can't see why we can't have both.
If you declare manually a foreign key, then selecting a table will only return the foreign key values and fetching the datas should be the user's responsability.  

> So feel free to send a PR.

I'll work on a proposal.

**Comment by moigagoo** [comment]
I have a couple of ideas regarding memory usage optimization. Like introducing lazy mode that would not automatically fetch related objects, or allowing Model fields to be nil. It's just that I don't have the opportunity to do all that unfortunately. Again, feel free to contribute.
